{% set repo_name = "spral" %}
{% set cxx_name = "lib" + repo_name %}
{% set version = "2025.01.08" %}

package:
  name: {{ cxx_name }}
  version: {{ version }}

source:
  - url: https://github.com/ralna/spral/archive/refs/tags/v{{ version }}.tar.gz
    sha256: c141878e36cb01a3c6f5e677a43d0f7781781755036f59ef91f38090a8f26f71
    patches:
      - increase_test_timeout.patch

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage(cxx_name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - pkg-config
    - meson
    - ninja
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - libhwloc
    - zlib
    - metis
  run:

test:
  commands:
    - test -f ${PREFIX}/include/spral.h  # [unix]
    - test -f ${PREFIX}/lib/libspral${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/ralna/spral
  license: BSD-3-Clause
  license_file: LICENCE
  summary: Sparse Parallel Robust Algorithms Library.

extra:
  feedstock-name: {{ repo_name }}
  recipe-maintainers:
    - traversaro
