{% set repo_name = "spral" %}
{% set cxx_name = "lib" + repo_name %}
{% set version = "2023.08.02" %}
{% set cuda_enabled = cuda_compiler_version != "None" %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}

{% set build_number = 1 %}

# The cpu version is installed by default
{% if cuda_enabled %}
{% set build_number = build_number + 200 %}
{% endif %}


package:
  name: {{ cxx_name }}
  version: {{ version }}

source:
  - url: https://github.com/ralna/spral/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 754500618b5da8404600c0bcc285cdcd0de62fa5676b8965e80253ccf7914598

build:
  skip: true  # [not linux]
  number: {{ build_number }}
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
  # The cpu version is installed by default
  track_features: {{ "[libspral-cuda]" if cuda_enabled else "" }}
  run_exports:
    - {{ pin_subpackage(cxx_name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - autoconf
    - automake
    - pkg-config
    - make
    - libgomp  # [linux]
  host:
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    # Ensure that we have a cuda-enabled libhwloc if CUDA is enabled
    # Workaround for https://github.com/conda-forge/libhwloc-feedstock/issues/64
    - libhwloc 2.9.1  # [cuda_compiler_version == "None"]
    - libhwloc 2.9.1=*cuda*  # [cuda_compiler_version != "None"]
    - zlib
    # workaround for https://github.com/conda-forge/metis-feedstock/issues/35
    - metis 5.1.0
  run:
    # workaround for https://github.com/conda-forge/metis-feedstock/issues/35
    - metis 5.1.0
    - libhwloc *=*cuda*  # [cuda_compiler_version != "None"]

test:
  commands:
    - test -f ${PREFIX}/include/spral.h  # [unix]
    - test -f ${PREFIX}/lib/libspral${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/ralna/spral
  license: BSD-3-Clause
  license_file: LICENCE
  summary:  Sparse Parallel Robust Algorithms Library.
  description: |
      This feedstock builds the spral library in the `libspral` conda package. Two variants of the package are built:

      * `cpu` in the build string: Without CUDA support, installed by default. Install specifically this version with `conda install libspral=*=*cuda*`.
      * `cuda` in the build string: With CUDA support. Install specifically this version with  `conda install libspral=*=*cuda*`



extra:
  feedstock-name: {{ repo_name }}
  recipe-maintainers:
    - traversaro
